### PR TITLE
TypeError: winston.transports.Loggly is not a constructor

### PR DESCRIPTION
**Pull request by mdemri**
Taking winston 2.4.0 doesn't work, so don't

### CODE REVIEW

**Comment by mostlyjason** [comment]
@mdemri can you offer more details about what error you found with Winston 2.4?

**Comment by mdemri** [comment]
Code:
const transports = [
    new (winston.transports.Console)({
        formatter(options) {
            // Return string will be passed to logger.
            return `${new Date()} ${options.level} ${options.message ? options.message : ''}`;
        },
    }),
];

if (condition) {
    require('winston-loggly-bulk');  // eslint-disable-line
    transports.push(
        new (winston.transports.Loggly)(_.assign(config, {
            isBulk: true,
            tags: ['blah', 'blahblah'],
        })));
}
const logger = new (winston.Logger)({
    transports,
});

Output:
new (winston.transports.Loggly)(_.assign(config, {

TypeError: winston.transports.Loggly is not a constructor

**Comment by mostlyjason** [comment]
Okay thanks we will have an engineer take a look at this in the next couple weeks

**Comment by mdemri** [comment]
Weeks?

It's an unprofessional behavior.
You're exposing your clients to bugs.

**Comment by mostlyjason** [comment]
Sorry we'd like to test it to confirm the bug or at least confirm others are affected, especially since minor version updates are supposed to be backwards compatible. We run sprints and it's at the top of our backlog. There are a few issues ahead of this one. If you get to it before us, we'd be grateful for a PR that fixes the issue as well.

**Comment by Shwetajain148** [comment]
@mdemri, I tried your sample code at my end to reproduce the issue mentioned by you but couldn't see any error. Can you please verify the below steps at your end to confirm that we both are following the same standard instructions for node logging. 

1. run the command **"npm install winston-loggly-bulk"** to setup the library.
2. Create an app.js file with the code- [app.txt](https://github.com/loggly/winston-loggly-bulk/files/1386958/app.txt)
3. Simply run your app.js file using command **node app.js**.

I tested the code with **winston version 2.4.0 and 2.3.1, node-loggly-bulk version 2.0.1 and 2.0.2, winston-loggly-bulk version 2.0.1, node version 6.10.1** and everything worked fine for me, my event also reached to Loggly successfully. 

FYI- The error **TypeError: winston.transports.Loggly is not a constructor** may also occur if the module **winston-loggly-bulk** couldn't be loaded in your project for any reason and is undefined. 

Please try the above steps and see if this resolve your issue?

cc: @mostlyjason

**Comment by adambiggs** [comment]
I'm also experiencing this error with winston `2.4.0` and winston-loggly-bulk `2.0.1` in node `8.7.0`.

**Comment by mostlyjason** [comment]
Thanks @adambiggs! @Shwetajain148 can you test these versions?

**Comment by Shwetajain148** [comment]
@adambiggs I tested with winston **2.4.0**, winston-loggly-bulk **2.0.1** in node **8.7.0** and **8.6.0** but couldn't see any error at my end. It would be great if you can offer your reproducible code to me so that I can look at the issue since I am not able to reproduce this error at my end. 

cc: @mostlyjason

**Comment by adambiggs** [comment]
Sorry @Shwetajain148, we've moved away from this package and I don't have time to look into it any further... But if it makes any difference I was using Yarn to install dependencies when I noticed the issue.

**Comment by Shwetajain148** [comment]
@adambiggs @mdemri I have tried in the ways provided by you(including Yarn) but couldn't reproduce this error on my end. If you ever come across with the reproducible code for this error in future please share it with me with the environment details, I will be happy to fix the issue. 

Thanks.

**Comment by mostlyjason** [comment]
@jimdubbs in your travisci environment, can you check the package lock or logs to see if the modules for winston-loggly-bulk and the dependency node-loggly-bulk were loaded? Also, which node version is it running?

**Comment by mbesnili** [comment]
This issue still occurs. I'm using node version 8.9.0, winston 2.4.0, winston-loggly-bulk 2.0.1

**Comment by mostlyjason** [comment]
@mbesnili can you paste your error message? Is it "winston.transports.Loggly is not a constructor"? Also, can you paste the code you are using to construct the loggly transport?

**Comment by Rubinski78** [comment]
Hi, i have the same error using the lib in node-red.
"**TypeError: transport is not a constructor**"

When i use the next statement it works
winston.add(winston.transports.Loggly, {
     token: "mytoken",
    subdomain: "mysubdomain",
     tags: ["test"],
     json:true
 });

but i need the var to do a .remove at the end.

Is there a workaround?

**this is my code:**

var require = global.get('require');

var winston = require('winston');
require('winston-loggly-bulk');

var loggly = new winston.transports.Loggly({
    token: "mytoken",
    subdomain: "mysubdomain",
    tags: ["test"],
    json:true
});

winston.add(loggly);

winston.log('info',"Hello World from Node.js!");
winston.remove(loggly);
//winlog.flushLogsAndExit();  --> causes node-red to crash

return msg;

**Comment by Shwetajain148** [comment]
Hi @mdemri @adambiggs @mbesnili can you please let me know the npm version you are running in your setup? It may possible that you are running an old version of npm which is causing this issue to you?

**Comment by Rubinski78** [comment]
I'm on npm version 3.10.10 

I will update to the newest version and inform you. 


Van: "Shwetajain148" <notifications@github.com> 
Aan: "loggly/winston-loggly-bulk" <winston-loggly-bulk@noreply.github.com> 
Cc: "Ruben Desmet" <ruben.desmet@telenet.be>, "Comment" <comment@noreply.github.com> 
Verzonden: Woensdag 29 november 2017 13:45:32 
Onderwerp: Re: [loggly/winston-loggly-bulk] don't take latest version of winston (#26) 



Hi [ https://github.com/mdemri | @mdemri ] [ https://github.com/adambiggs | @adambiggs ] [ https://github.com/mbesnili | @mbesnili ] can you please let me know the npm version you are running in your setup? It may possible that you are running an old version of npm which is causing this issue to you?

**Comment by Shwetajain148** [comment]
@Rubinski78 I was able to reproduce the error reported by you if I follow your exact code. So what happening here is that if you are creating the Loggly transporter using the new keyword and storing it into a variable(to do `.remove()` later) then you are instantly creating an instance of it. Since the add method of winston may take 3 parameters like `add(transport: TransportInstance, options?: TransportOptions, created?: boolean): LoggerInstance;` you have to pass 2 more parameter while doing `winston.add()` like `winston.add(loggly, null, true);` to tell the winston that you have already created an instance of Loggly transporter. You can refer the below code line for more clarity. 

Ref- https://github.com/winstonjs/winston/blob/2.4.0/lib/winston/logger.js#L481

Please follow the below code that should works for you and if not then let me know.

```
const winston = require('winston');
var winlog = require('winston-loggly-bulk');

var loggly = new winston.transports.Loggly({
    token: "loggly-token",
    subdomain: "loggly-subdomain",
    tags: ["test"],
    json: true
});

winston.add(loggly, null, true);

winston.log('info', "Hello World from Node.js!");
winston.remove(loggly);
winlog.flushLogsAndExit();
```
Also, please note that if you are using the `flushLogsAndExit()` method of `winston-loggly-bulk` then you have to do something like `var winlog = require('winston-loggly-bulk');` and then you will be able to do `winlog.flushLogsAndExit();`.

**Comment by mostlyjason** [comment]
Hey guys we have updated our documentation to explain using the new keyword, and we've also created a troubleshooting step addressing the error message: https://www.loggly.com/docs/node-js-logs/. Since we haven't seen any additional reports since describing the fix, I'm going to close this issue for now. Please reopen it if you experience the issue after implementing Shweta's solution.

**Pull request closed without merging**
